import SearchSection from "@/components/SearchSection";

export const metadata = {
  title: "Search - Metflix",
  description: "Generated by create next app",
};

export default async function SearchPage() {
  return (
    <div className="mt-20">
      <SearchSection />
    </div>
  );
}
