import SearchSection from "@/components/SearchSection";

export const metadata = {
  title: "Search - Metflix",
  description: "Generated by create next app",
};

export type Props = {
  params: {};
  searchParams?: { [key: string]: string | string[] | undefined };
};

export default async function SearchPage({ params, searchParams }: Props) {
  const query = searchParams?.q?.toString() ?? "";

  return (
    <div className="mt-20">
      {JSON.stringify(searchParams)}
      <SearchSection query={query} />
    </div>
  );
}
