import BannerSection from "@/components/BannerSection";
import MoviesCarousel, {
  Props as MoviesCarouselProp,
} from "@/components/ImageCarousel/MoviesCarousel";

export const metadata = {
  title: "Movies - Metflix",
  description: "Generated by create next app",
};

export default async function MoviesPage() {
  const moviesCarousel: MoviesCarouselProp[] = [
    {
      title: "Trending Today",
      href: "/",
      type: "trending",
    },
    {
      title: "Now Playing",
      href: "/",
      type: "now_playing",
    },
    {
      title: "Upcoming",
      href: "/",
      type: "upcoming",
    },
    {
      title: "Popular",
      href: "/",
      type: "popular",
    },
    {
      title: "Top Rated",
      href: "/",
      type: "top_rated",
    },
  ];
  return (
    <>
      <BannerSection media="movie" type="popular" />

      <ul className="flex flex-col gap-6 lg:gap-7">
        {moviesCarousel.map((movieCarousel, index) => (
          <li key={index}>
            <MoviesCarousel
              key={index}
              title={movieCarousel.title}
              href={movieCarousel.href}
              type={movieCarousel.type}
            />
          </li>
        ))}
      </ul>
    </>
  );
}
