import BannerSection from "@/components/BannerSection";
import TrendingNowMovies from "@/components/Movies/TrendingNow";
import TopRatedMovies from "@/components/Movies/TopRatedMovies";
import TopRatedTVShows from "@/components/Movies/TopRatedTVShows";
import MoviesCarousel from "@/components/Movies";
import { MovieType } from "@/api/types";

export const metadata = {
  title: "Movies - Metflix",
  description: "Generated by create next app",
};

export type MovieCarousels = {
  title: string;
  href: string;
  type: MovieType;
}[];

export default async function MoviesPage() {
  const movieCarousels: MovieCarousels = [
    {
      title: "Trending Today",
      href: "/",
      type: "trending",
    },
    {
      title: "Now Playing",
      href: "/",
      type: "now_playing",
    },
    {
      title: "Upcoming",
      href: "/",
      type: "upcoming",
    },
    {
      title: "Popular",
      href: "/",
      type: "popular",
    },
    {
      title: "Top Rated",
      href: "/",
      type: "top_rated",
    },
  ];
  return (
    <>
      <BannerSection media="movie" type="popular" />

      <ul className="flex flex-col gap-[3vw]">
        {movieCarousels.map((movieCarousel, index) => (
          <li>
            <MoviesCarousel
              key={index}
              title={movieCarousel.title}
              href={movieCarousel.href}
              type={movieCarousel.type}
            />
          </li>
        ))}
      </ul>
    </>
  );
}
