import BannerSection from "@/components/BannerSection";
import TrendingNowMovies from "@/components/Movies/TrendingNow";
import TopRatedMovies from "@/components/Movies/TopRatedMovies";
import TopRatedTVShows from "@/components/Movies/TopRatedTVShows";

export const metadata = {
  title: "Movies - Metflix",
  description: "Generated by create next app",
};

export default async function MoviesPage() {
  return (
    <>
      <BannerSection />

      <div className="flex flex-col gap-[3vw]">
        <TrendingNowMovies />

        <TopRatedMovies />

        <TopRatedTVShows />
      </div>
    </>
  );
}
