import Navbar from "@/components/Navbar";
import { Open_Sans } from "@next/font/google";
import "@/css/globals.css";

const openSans = Open_Sans({
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`bg-black text-slate-100 antialiased ${openSans.className}`}
      >
        <Navbar />

        <main className="px-8">{children}</main>
      </body>
    </html>
  );
}
