import { getCredits, getTVShow } from "@/lib/tmdb";

import DetailsBanner from "@/components/DetailsBanner";
import TVShowsCarousel from "@/components/ImageCarousel/TVShowsCarousel";
import type { Props as TVShowsCarouselProp } from "@/components/ImageCarousel/TVShowsCarousel";
import SectionHeading from "@/components/SectionHeading";
import ImageCarousel from "@/components/Carousel";

export const metadata = {
  title: "Movie - Metflix",
  description: "Generated by create next app",
};

export type Props = {
  params: {
    id: string;
  };
};

export default async function MoviesPage({ params }: Props) {
  const { id } = params;

  const tvShow = await getTVShow(id);
  if (!tvShow) throw new Error("No tvShow Found!");

  const credits = await getCredits(id, "movie");
  const castList = credits?.cast || [];

  const tsShowsCarousel: TVShowsCarouselProp[] = [
    {
      title: "Similar TV Shows",
      type: "similar",
    },
    {
      title: "Recommended TV Shows",
      type: "recommendations",
    },
  ];

  return (
    <>
      <DetailsBanner item={tvShow} media={"tv"} />

      <ul className="flex flex-col gap-[3vw]">
        {!!castList.length && (
          <li>
            <section>
              <SectionHeading> Meet the Cast </SectionHeading>

              <ImageCarousel
                items={castList.map((cast) => ({
                  id: cast.id,
                  postImg: `https://image.tmdb.org/t/p/w500${cast.profile_path}`,
                  title: cast.name,
                  details: cast.character ? (
                    <span className="text-sm italic text-stone-200">
                      As {cast.character}
                    </span>
                  ) : (
                    <></>
                  ),
                }))}
              />
            </section>
          </li>
        )}

        {!!tvShow.seasons.length && (
          <li>
            <section>
              <SectionHeading> Seasons </SectionHeading>

              <ImageCarousel
                items={tvShow.seasons.map((season) => ({
                  id: season.id,
                  postImg: `https://image.tmdb.org/t/p/w500${season.poster_path}`,
                  title: season.name,
                  details: (
                    <div className="flex items-center gap-1 text-sm text-stone-200">
                      {new Date(season.air_date).getFullYear()}
                      {" · "}
                      {season.episode_count} Episodes
                    </div>
                  ),
                }))}
              />
            </section>
          </li>
        )}

        {tsShowsCarousel.map((tvShowCarousel, index) => (
          <li key={index}>
            <TVShowsCarousel
              key={index}
              id={id.toString()}
              title={tvShowCarousel.title}
              href={tvShowCarousel.href}
              type={tvShowCarousel.type}
            />
          </li>
        ))}
      </ul>
    </>
  );
}

export const dynamicParams = true;
export const revalidate = 86400;

export async function generateStaticParams() {
  const tempIds = [603692, 4, 5];
  return tempIds.map((id) => ({
    id,
  }));
}
