import { MOVIE_TYPES } from "@/api/constants";
import type { MovieType } from "@/api/types";

import MoviesList from "@/components/ImageList/MoviesList";

export const metadata = {
  title: "Movies - Metflix",
  description: "Generated by create next app",
};

export type Props = {
  params: {
    type: MovieType;
  };
};

export default async function MoviesPage({ params }: Props) {
  const { type } = params;

  return (
    <div className="mt-20">
      <MoviesList title={`${type.replaceAll("_", " ")} Movies`} type={type} />;
    </div>
  );
}

export const dynamicParams = false;
export const revalidate = 86400;

export async function generateStaticParams() {
  return MOVIE_TYPES.map((type) => ({
    type,
  }));
}
