import BannerSection from "@/components/BannerSection";
import TVShowsCarousel, {
  Props as TVShowsCarouselProp,
} from "@/components/ImageCarousel/TVShowsCarousel";

export const metadata = {
  title: "TV Shows - Metflix",
  description: "Generated by create next app",
};

export default async function MoviesPage() {
  const tvShowsCarousel: TVShowsCarouselProp[] = [
    {
      title: "Trending Today",
      href: "/",
      type: "trending",
    },
    {
      title: "Popular",
      href: "/",
      type: "popular",
    },
    {
      title: "Top Rated",
      href: "/",
      type: "top_rated",
    },
    {
      title: "New Releases",
      href: "/",
      type: "on_the_air",
    },
  ];
  return (
    <>
      <BannerSection media="tv" type="popular" />

      <ul className="flex flex-col gap-[3vw]">
        {tvShowsCarousel.map((movieCarousel, index) => (
          <li>
            <TVShowsCarousel
              key={index}
              title={movieCarousel.title}
              href={movieCarousel.href}
              type={movieCarousel.type}
            />
          </li>
        ))}
      </ul>
    </>
  );
}
