import { TV_TYPES } from "@/tmdb/constants";

import TVShowsList from "@/components/ImageList/TVShowsList";
import type { TVType } from "@/tmdb/types/tv";

export const metadata = {
  title: "Movies - Metflix",
  description: "Generated by create next app",
};

export type Props = {
  params: {
    type: TVType;
  };
};

export default async function MoviesPage({ params }: Props) {
  const { type } = params;

  return (
    <div className="mt-20">
      <TVShowsList
        title={`${type.replaceAll("_", " ")} TV Shows`}
        type={type}
      />
    </div>
  );
}

export const dynamicParams = false;
export const revalidate = 86400;

export async function generateStaticParams() {
  return TV_TYPES.map((type) => ({
    type,
  }));
}
