 name: SST workflow
 on: push

 # Concurrency group name ensures concurrent workflow runs wait for any in-progress job to finish
 concurrency:
   group: merge-${{ github.ref }}

 permissions:
   id-token: write # This is required for requesting the JWT
   contents: read # This is required for actions/checkout

 jobs:
   DeployApp:
     runs-on: ubuntu-latest
     env:
      # Define your envs needed for static generation:
      ENV_NAME: ${{ secrets.ENV_NAME }}

     steps:
        - name: Git clone the repository
          uses: actions/checkout@v3

        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
            role-to-assume: arn:aws:iam::527297456672:role/Github
            role-duration-seconds: 14390 # adjust as needed for your build time
            aws-region: us-east-1
           
        - name: Install pnpm
          uses: pnpm/action-setup@v4
          with:
            version: 8
            run_install: false

        - name: Get pnpm store directory
          shell: bash
          run: echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

        - name: Setup pnpm cache
          uses: actions/cache@v4
          with:
            path: ${{ env.STORE_PATH }}
            key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
            restore-keys: ${{ runner.os }}-pnpm-store-

        - name: Installing my packages
          run: pnpm i

        - name: Deploy app
          run: npx sst deploy --stage prod